spring:
  data:
    mongodb:
      host: 106.13.162.44
      port: 27017
      database: tools
#  security:
#    user:
#      name: admin
#      password: ${spring.application.name:admin-password}
#      password-e: admin-eureka
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true #jackson返回date为日期时间戳